### ISSUE TITLE
App crash caused by mparticle: FATAL EXCEPTION - No virtual method getInfo()

### ISSUE THREAD

**Issue by osvald0** [mParticle/mparticle-android-sdk#142]
The app was working fine until yesterday. This error was caused by the last update I think.
I'm mparticle + branch.

Environment:
Mac.
Java 11.
Android Studio Bumblebee 2021.1.1 Patch 3.
Kotlin Version 1.6.10
Gradle 7.0.4
TargetSDK 31

<img width="2366" alt="Screen Shot 2022-05-18 at 14 36 17" src="https://user-images.githubusercontent.com/20977158/169109337-4e60c950-309e-4a7f-add8-d5103d5f738a.png">

**Comment by willpassidomo** [comment]
@osvald0 `MPEvent.getInfo()` was previously deprecated and was fully removed in version 5.39.0.

To fix, replace your usage of `getInfo()` with `getCustomAttributes()` (as wall as `info(Map<>)` -> `customAttributes(Map<>)`)

**Comment by willpassidomo** [comment]
Hey @osvald0 , thanks for reporting. 

This should only happen if your `optimizely-kit` version is out of sync with `android-core`. Could you provide the version you are using for both?

Since this method, `getInfo()` was removed in version 5.39.0, I would guess the state is something like `android-core` = 5.39.0 and `optimizely-kit` < 5.39.0

**Comment by willpassidomo** [comment]
@osvald0 my bad, I replaced my original response, when I realized I misread your report the first time through 😬

**Comment by osvald0** [comment]
@willpassidomo I was using the `optimizely-kit` version 5.20.0.
I moved to use `5+` and It's working now.

Thanks!

**Comment by willpassidomo** [comment]
Awesome! Glad that solved it. Thanks again for reporting :)
