### ISSUE TITLE
Cannot upload messages after upgrading from 4.15 to 5.2.0

### ISSUE THREAD

**Issue by EDLuke** [mParticle/mparticle-android-sdk#21]
Hi,

I have recently changed from version 4.15 to 5.2.0 and can no longer upload messages to LiveStream. `VERBOSE` logging is not providing any information either. On 4.15 I was occasionally getting

`android.database.sqlite.SQLiteException: Can't downgrade database from version 8 to 6` 

in the logs but cannot find relevant errors/exceptions  in 5.2.0. Any ideas?

**Comment by samdozor** [comment]
hey @EDLuke if you were ever getting `Can't downgrade database from version 8 to 6`, that means you must have installed an app with SDK version 5, then installed/downgrade to an app with version 4, which is not supported. It sounds like you then installed an app with version 5 again on top of that.

We do not support downgrading from 5 to 4 and then upgrading back again as this should never happen in a production environment. With that in mind - can you try the following:

### Verification 1

1. **Completely remove the app from the device**
2. Install the old version of the app with 4.15.
3. Install the new version of the app implemented with SDK v5
4. Confirm uploads occur as expected.

### Verification 2

1. **Completely remove the app from the device**
2. Install the new version of the app implemented with SDK v5
3. Confirm uploads occur as expected

Thanks!

**Comment by EDLuke** [comment]
You got the scenario right. Upload works in both verification cases. Uninstalling apps did the trick. Thanks!

**Comment by EDLuke** [comment]
Sorry got too excited to see activities in the Live Stream. I am still not able to see any events from

`MParticle.getInstance().logEvent()`

The only events showing up in the Live Stream is currently `Session Start`, `Session End` and `Application State Transition`. I have tried `MParticle.getInstance().upload()` but to no avail.

**Comment by samdozor** [comment]
hey @EDLuke custom events/session start/end/ASTs all go through the same pipeline, so if you see one I'd expect you to see all. For what it's worth, I'll point out that production data will not be displayed in the livestream, if you're setting the SDK to production mode.

Since there are so many things that could be going on here, I think the best way to move forward from here is get you connected with our CS team to troubleshoot. Please reach out to us via support@mparticle.com and we'll get you routed to a human ASAP.
