### ISSUE TITLE
Unable to start mParticle off main thread

### ISSUE THREAD

**Issue by josh-bartz** [mParticle/mparticle-android-sdk#343]
Related to #310 . To avoid the IO on main thread violations, I attempted to call MParticle.start() using `Dispatchers.IO`. Unfortunately, this caused mParticle to not send any events. Version 5.44.1.

**Comment by samdozor** [comment]
This is by design as we along with several kits need to immediately subscribe to Activity lifecycle events in order to have accurate session management. The design of the SDK is that it should be fast to start on the main thread, deferring as much as possible to its various background threads or future run-loops. In the linked issue, the only potential issue is the usage of SharedPreferences, which at this time we do rely on. Please see that linked issue for more details.
