### ISSUE TITLE
App Crashing on 1st time opening, After downloading from Play store

### ISSUE THREAD

**Issue by bapu** [mParticle/mparticle-android-sdk#40]
My App is crashing when the user is installing the app from Play store for 1st time, on subsequent re-open it works fine. Below is the error log. (No issues when we are installing local package)

java.lang.RuntimeException: Unable to instantiate receiver com.mparticle.ReferrerReceiver: java.lang.ClassNotFoundException: Didn't find class "com.mparticle.ReferrerReceiver" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.xx.mobile.android.na-WbflupEx4Uuxh4hi_Stk-A==/base.apk"],nativeLibraryDirectories=[/data/app/com.xx.mobile.android.na-WbflupEx4Uuxh4hi_Stk-A==/lib/arm64, /data/app/com.xx.mobile.android.na-WbflupEx4Uuxh4hi_Stk-A==/base.apk!/lib/arm64-v8a, /system/lib64]]

**Comment by NoRoboto** [comment]
The same happens on our app.
using implementation 'com.mparticle:android-core:5.12.5'

**Comment by samdozor** [comment]
Hi! Thanks for the report. Do you still have `ReferrerReceiver` located in your AndroidManifest.xml? That might be the issue. Google has deprecated the usage of the install referrer intent and we have removed that class for our SDK. You can see the latest docs for receiving the install referrer string here: https://github.com/mParticle/mparticle-android-sdk#google-play-install-referrer

**Comment by NoRoboto** [comment]
Yes, we have `<receiver android:name="com.mparticle.ReferrerReceiver" android:exported="true">` on our AndroidManiifest.xml

let's try it, when we have an update I will let you know, thanks.

**Comment by NoRoboto** [comment]
It works, just remove `<receiver android:name="com.mparticle.ReferrerReceiver" android:exported="true">` and add `implementation 'com.android.installreferrer:installreferrer:1.0'`
as mentioned on https://github.com/mParticle/mparticle-android-sdk#google-play-install-referrer.

Thank you.

**Comment by CamiloVega** [comment]
@willpassidomo I am unfortunately still seeing this, made sure i do not have the ReferrerReceiver, I was trying to update to 5.14.9 given the high crash rate we are seeing from https://github.com/mParticle/mparticle-android-sdk/issues/53 but after the updating the version from 5.11, i see this crash

**Comment by willpassidomo** [comment]
@CamiloVega ReferrerReceiver was deprecated and removed in version `5.12.3`. Unfortunately, since it is only referenced by the `AndroidMainfest.xml` the application will fail at runtime instead of at compile time when this class isn't present. The best solution we could come up with to prevent missing this update becoming a problem for our customers, was to implement and ship a custom lint check which should error when `ReferrerReceiver` is registered in the manifest, but not present in the SDK.

The current method of receiving Install Referrer data is to use the Google Play `install-referrer` library which is outlined in our docs: https://github.com/mParticle/mparticle-android-sdk#google-play-install-referrer
