### ISSUE TITLE
MParticle.getInstance() returns null on Kitkat

### ISSUE THREAD

**Issue by rwozniak** [mParticle/mparticle-android-sdk#43]
Hi, on Android SDK version 19 the `MParticle.getInstance()` always returns null despite properly initialising it (calling `MParticle.getInstance()` in `Application.onCreate()`).

There are no error logs produced by mParticle in this situation, session seems to start correctly:
`D/mParticle: Started new session`

This problem does not exist on more recent versions of Android SDK.

**Comment by willpassidomo** [comment]
Hey @rwozniak. I'm not sure exactly why `MParticle.getInstance()` is returning null, but a very common problem on KitKat devices we see stems from TLS 1.2 not being enabled by default. In order to enable TLS 1.2, which our servers require for incoming requests as part of our security practices, you will need to run:

```
ProviderInstaller.installIfNeededAsync(this, new ProviderInstaller.ProviderInstallListener() {
            @Override
            public void onProviderInstalled() { }
            @Override
            public void onProviderInstallFailed(int i, Intent intent) { }
});
```
within your applications initialization code. This requires Google Play Services. There is an alternative sync method available if needed, `ProviderInstaller.installIfNeeded(Context)`

Let me know if you've already done this and the problem persists

**Comment by willpassidomo** [comment]
closing this for now
