### ISSUE TITLE
MParticleOptions.Builder enableUncaughtExceptionLogging does not work

### ISSUE THREAD

**Issue by emmaChristine** [mParticle/mparticle-android-sdk#64]
Getting this error:
`Configuration: No string resource for: mp_reportUncaughtExceptions, using default: false`

SDK Versions: "5.16.5" and "5.16.0"
Can anyone assist?

**Comment by willpassidomo** [comment]
Hey @emmaChristine, thanks for bringing this up! I just read through that section of the code and ran a few tests, what I saw was that the `MParticleOptions.enableUncaughtExceptionLogging` **does** that effect and this is just poorly worded log message. 

We maintain some logic that merges settings from the static xml config file, and `MParticleOptions`. This message is missing the context that it is using the default value of `false` for the static xml config file _before_ we merge the settings. During the merge, MParticleOptions configurations will take precedence.

I just want to confirm, since I may have missed it, are you noticing that uncaught exceptions are actually not being logged, or was it just the log message?

**Comment by emmaChristine** [comment]
Hello @willpassidomo Thanks so much for coming back to me.
As a matter of fact I haven't noticed any uncaught exceptions at all, I was just put off by the log message, therefore I wasn't sure if the flag was usable.

I see what you mean, so I will go and use the flag then.

Emma

**Comment by willpassidomo** [comment]
No problem, I believe the xml config settings are deprecated or ready to be deprecated, so look for this to disappear in a future version :)
